import project01 from "./../img/projects/01.jpg";
import project01Big from "./../img/projects/01-big.jpg";

import project02 from "./../img/projects/02.jpg";
import project02Big from "./../img/projects/02-big.jpg";

import project03 from "./../img/projects/03.jpg";
import project03Big from "./../img/projects/03-big.jpg";

import project04 from "./../img/projects/04.jpg";
import project04Big from "./../img/projects/04-big.jpg";

import project05 from "./../img/projects/05.jpg";
import project05Big from "./../img/projects/05-big.jpg";

import project06 from "./../img/projects/06.jpg";
import project06Big from "./../img/projects/06-big.jpg";

const projects = [
    {
        specialty: "Младший разработчик",
        description: "Участие в разработке веб-приложений с использованием Python и JavaScript в команде опытных разработчиков. Стажер будет знакомиться с современными методологиями разработки, работать с системами контроля версий и участвовать в планировании задач. Практика подходит для студентов IT-специальностей, желающих погрузиться в реальные проекты.",
        img: project01,
        imgBig: project01Big,
        date: "01.11.2024 - 31.01.2025",
        university: "Уральский Федеральный Университет",
        link_university: "https://urfu.ru/ru/",
        company: "IT Solutions Inc.",
        link_company: "https://www.itsolutions.co.uk",
        industry: "Информационные технологии, системная интеграция, интернет",
        salary: 30000,
        employmentType: "Полная занятость",
        education: "Высшее",
        internshipFormat: "Очно",
        places: 3
    },
    {
        specialty: "Специалист по тестированию",
        description: "Проведение функционального и регрессионного тестирования программного обеспечения, работа с баг-трекинговыми системами. Стажер будет разрабатывать тестовые сценарии, анализировать результаты тестирования и взаимодействовать с командой разработчиков для улучшения качества продукта. Подходит для студентов, стремящихся к карьере в QA.",
        img: project02,
        imgBig: project02Big,
        date: "01.12.2024 - 28.02.2025",
        university: "Высшая школа экономики",
        link_university: "https://www.hse.ru",
        company: "Tech Quality Group",
        link_company: "https://www.tqg.de/en/",
        industry: "Информационные технологии, системная интеграция, интернет",
        salary: 25000,
        employmentType: "Полная занятость",
        education: "Высшее",
        internshipFormat: "Дистанционно",
        places: 5
    },
    {
        specialty: "Аналитик данных",
        description: "Сбор, обработка и анализ больших объемов данных для бизнес-решений. Стажер будет использовать инструменты Excel, SQL и Python для обработки информации, создание отчетов и визуализации данных. Практика предназначена для студентов, заинтересованных в аналитике и работе с данными.",
        img: project03,
        imgBig: project03Big,
        date: "15.11.2024 - 15.02.2025",
        university: "Уральский Федеральный Университет",
        link_university: "https://urfu.ru/ru/",
        company: "Data Insights Ltd.",
        link_company: "https://find-and-update.company-information.service.gov.uk/company/12829078",
        industry: "Информационные технологии, системная интеграция, интернет",
        salary: 35000,
        employmentType: "Неполная занятость",
        education: "Высшее",
        internshipFormat: "Дистанционно",
        places: 10
    },
    {
        specialty: "Аналитик данных",
        description: "Поддержка и администрирование IT-инфраструктуры компании, включая настройку серверов, управление сетевым оборудованием и решение инцидентов. Стажер будет учиться обеспечивать бесперебойную работу систем и сети, а также взаимодействовать с пользователями для устранения проблем.",
        img: project04,
        imgBig: project04Big,
        date: "01.10.2024 - 30.12.2024",
        university: "Московский физико-технический институт",
        link_university: "https://mipt.ru",
        company: "Reliable Systems",
        link_company: "https://www.linkedin.com/company/reliable-systems",
        industry: "Информационные технологии, системная интеграция, интернет",
        salary: 40000,
        employmentType: "Полная занятость",
        education: "Высшее",
        internshipFormat: "Очно",
        places: 10
    },
    {
        specialty: "UX/UI дизайнер",
        description: "Проектирование пользовательских интерфейсов и взаимодействия для веб- и мобильных приложений. Стажер будет работать над созданием прототипов, проводить пользовательские тестирования и вносить изменения на основе отзывов пользователей. Практика подойдёт для креативных студентов с интересом к дизайну и пользовательскому опыту.",
        img: project05,
        imgBig: project05Big,
        date: "01.11.2024 - 28.01.2025",
        university: "Екатеринбургская академия современного искусства",
        link_university: "https://еаси.екатеринбург.рф",
        company: "Creative Design Studio",
        link_company: "https://find-and-update.company-information.service.gov.uk/company/12829078",
        industry: "Информационные технологии, системная интеграция, интернет",
        salary: "не предусмотрена",
        employmentType: "Полная занятость",
        education: "Высшее",
        internshipFormat: "Дистанционно",
        places: 7
    },
    {
        specialty: "Ассистент аналитика",
        description: "Помощь в подготовке финансовых отчетов, анализ данных и исследование рынка. Стажер будет заниматься сбором информации, анализом данных и подготовкой презентаций для команды. Эта практика поможет развить навыки аналитического мышления и глубокого понимания",
        img: project06,
        imgBig: project06Big,
        date: "01.11.2024 - 31.01.2025",
        university: "Уральский Федеральный Университет",
        link_university: "https://urfu.ru/ru/",
        company: "Finance Analytics Corp.",
        link_company: "https://find-and-update.company-information.service.gov.uk/company/12829078",
        industry: "Финансовый сектор",
        salary: "25000",
        employmentType: "Полная занятость",
        education: "Высшее",
        internshipFormat: "Дистанционно",
        places: 10
    },
    {
        specialty: "Специалист по кредитованию",
        description: "Оценка кредитных заявок и консультирование клиентов по вопросам кредитования. Стажер будет анализировать финансовые документы, оценивать риски и принимать участие в процессе выдачи кредитов. Эта практика подойдёт для студентов, желающих развить свои навыки в области кредитного анализа и работы с клиентами.",
        img: project05,
        imgBig: project05Big,
        date: "01.12.2024 - 28.02.2025",
        university: "Уральский Государственный Экономический Университет",
        link_university: "https://www.usue.ru",
        company: "Credit Solutions Group",
        link_company: "https://creditsolutions.ru",
        industry: "Финансовый сектор",
        salary: "30000",
        employmentType: "Полная занятость",
        education: "Высшее",
        internshipFormat: "Дистанционно",
        places: 15
    },
    {
        specialty: "Бухгалтер-стажер",
        description: "Ведение бухгалтерского учета, работа с первичной документацией и участие в составлении финансовых отчетов. Стажер будет осваивать программы для учета и научится проводить инвентаризацию. Практика идеальна для студентов, желающих углубиться в бухгалтерский учет и финансовую отчетность.",
        img: project05,
        imgBig: project05Big,
        date: "15.11.2024 - 15.02.2025",
        university: "Уральский Государственный Экономический Университет",
        link_university: "https://www.usue.ru",
        company: "Accounting Solutions Ltd.",
        link_company: "https://accountingsolutions.ru",
        industry: "Финансовый сектор",
        salary: "20000",
        employmentType: "Неполная занятость",
        education: "Высшее",
        internshipFormat: "Очно",
        places: 5
    },
    {
        specialty: "Финансовый консультант",
        description: "Консультирование клиентов по вопросам инвестиций, сбережений и финансового планирования. Стажер будет помогать в подготовке индивидуальных финансовых планов и участвовать в встречах с клиентами. Практика предназначена для студентов, интересующихся финансовыми услугами и клиентским обслуживанием.",
        img: project05,
        imgBig: project05Big,
        date: "01.10.2024 - 30.12.2024",
        university: "Уральский Федеральный Университет",
        link_university: "https://urfu.ru/ru/",
        company: "Financial Advisory Group",
        link_company: "https://accountingsolutions.ru",
        industry: "Финансовый сектор",
        salary: "не предусмотрена",
        employmentType: "Неполная занятость",
        education: "Среднее профессиональное",
        internshipFormat: "Очно",
        places: 12
    },
    {
        specialty: "Специалист по налогам",
        description: "Подготовка налоговых деклараций, анализ налоговых обязательств и консультирование по налоговым вопросам. Стажер будет изучать налоговое законодательство и применять его на практике. Эта практика подойдёт для студентов, желающих развить навыки в налоговом учете и консультировании.",
        img: project05,
        imgBig: project05Big,
        date: "01.11.2024 - 28.01.2025",
        university: "Уральский Государственный Экономический Университет",
        link_university: "https://www.usue.ru",
        company: "Tax Consulting Services",
        link_company: "https://taxconsulting.ru",
        industry: "Финансовый сектор",
        salary: 30000,
        employmentType: "Неполная занятость",
        education: "Высшее",
        internshipFormat: "Дистанционно",
        places: 8
    },
    {
        specialty: "Журналист-стажер",
        description: "Подготовка и написание материалов для новостных публикаций, работа с источниками информации и проведение интервью. Стажер будет изучать основы журналистского мастерства, учиться формировать и представлять актуальные темы. Практика идеально подходит для студентов, желающих развить свои навыки в журналистике и коммуникации.",
        img: project05,
        imgBig: project05Big,
        date: "01.11.2024 - 31.01.2025",
        university: "Уральский Федеральный Университет",
        link_university: "https://urfu.ru/ru/",
        company: "News Agency Ural",
        link_company: "https://newsural.ru",
        industry: "СМИ, маркетинг, реклама, BTL, PR, дизайн, продюсирование",
        salary: 30000,
        employmentType: "Неполная занятость",
        education: "Высшее",
        internshipFormat: "Дистанционно",
        places: 8
    },
    {
        specialty: "Редактор контента",
        description: "Проверка и редактирование материалов перед публикацией, работа с журналистами и создание редакционных планов. Стажер будет разрабатывать стандарты качества для контента и анализировать реакции аудитории. Практика подойдет для студентов, заинтересованных в медиапроизводстве и редактур",
        img: project05,
        imgBig: project05Big,
        date: "01.12.2024 - 28.02.2025",
        university: "Уральский Федеральный Университет",
        link_university: "https://urfu.ru/ru/",
        company: "Media House Ural",
        link_company: "https://mediahouse.ru",
        industry: "СМИ, маркетинг, реклама, BTL, PR, дизайн, продюсирование",
        salary: "не предусмотрена",
        employmentType: "Неполная занятость",
        education: "Среднее профессиональное",
        internshipFormat: "Очно",
        places: 3
    },
    {
        specialty: "Копирайтер",
        description: "Написание статей, пресс-релизов и контента для социальных сетей. Стажер будет заниматься разработкой креативных идей и написанием текстов, соответствующих редакционным стандартам. Практика идеальна для студентов, стремящихся развить свои навыки в копирайтинге и контент-маркетинге.",
        img: project05,
        imgBig: project05Big,
        date: "15.11.2024 - 15.02.2025",
        university: "Уральский Федеральный Университет",
        link_university: "https://urfu.ru/ru/",
        company: "Creative Media Group",
        link_company: "https://creativemedia.ru",
        industry: "СМИ, маркетинг, реклама, BTL, PR, дизайн, продюсирование",
        salary: 20000,
        employmentType: "Неполная занятость",
        education: "Высшее",
        internshipFormat: "Дистанционно",
        places: 2
    },
    {
        specialty: "Фотограф",
        description: "Съемка событий, интервью и создание фотоматериалов для новостей. Стажер будет развивать свои навыки в фотографии, учиться работать с фотоаппаратом и постобработкой изображений. Практика подходит для студентов, заинтересованных в визуальной журналистике.",
        img: project05,
        imgBig: project05Big,
        date: "01.10.2024 - 30.12.2024",
        university: "Уральский Федеральный Университет",
        link_university: "https://urfu.ru/ru/",
        company: "Photo Journal",
        link_company: "https://photojournal.ru",
        industry: "СМИ, маркетинг, реклама, BTL, PR, дизайн, продюсирование",
        salary: 20000,
        employmentType: "Полная занятость",
        education: "Высшее",
        internshipFormat: "Очно",
        places: 3
    },
    {
        specialty: "Специалист по PR",
        description: "Разработка и реализация PR-кампаний, взаимодействие с медиа и управление репутацией компании. Стажер будет участвовать в создании пресс-релизов и анализе эффективности PR-акций. Практика подойдёт для студентов, желающих углубить свои знания в области PR и связей с общественностью.",
        img: project05,
        imgBig: project05Big,
        date: "01.11.2024 - 28.01.2025",
        university: "Уральский Федеральный Университет",
        link_university: "https://pragencyural.ru",
        company: "PR Agency Ural",
        link_company: "https://photojournal.ru",
        industry: "СМИ, маркетинг, реклама, BTL, PR, дизайн, продюсирование",
        salary: 50000,
        employmentType: "Полная занятость",
        education: "Высшее",
        internshipFormat: "Очно",
        places: 2
    },
];

export {projects}